apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi  # Adjust the size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-08efd7f2e0974a136.efs.us-east-1.amazonaws.com  
    path: "/"  # Root directory of your EFS

