apiVersion: v1
kind: Service
metadata:
  name: efs-service
spec:
  selector:
    app: efs-app  # Use the same label as in your Pod deployment
  ports:
    - protocol: TCP
      port: 2049  # Default port for NFS
      targetPort: 2049
  type: ClusterIP 
